### ISSUE TITLE
Enable CI Status on Pull Requests

### ISSUE THREAD

**Issue by zqzhang** [crosswalk-project/crosswalk-test-suite#1680]
https://github.com/w3c/web-platform-tests has enabled https://travis-ci.org/w3c/web-platform-tests to automatically check every pull request. This is a good practice. Let's enable this continuous integration service here.

Some references:
- https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.md#ci-status-on-pull-requests
- https://github.com/blog/1227-commit-status-api
- https://developer.github.com/v3/repos/statuses/

**Comment by zqzhang** [comment]
@haoxli

**Comment by haoxli** [comment]
@kangxu  Please spend some effort on this recently.

**Comment by zqzhang** [comment]
Because we cannot access to the setting of this repository, let's stop the task.

**Comment by kangxu** [comment]
Step1:
![image](https://cloud.githubusercontent.com/assets/7007826/11290452/c977720a-8f71-11e5-99ea-84c8b30c2e34.png)

**Comment by kangxu** [comment]
Step2:
![image](https://cloud.githubusercontent.com/assets/7007826/11290464/e0234768-8f71-11e5-8a5a-225e85ce5a6a.png)

**Comment by kangxu** [comment]
Step3:
![image](https://cloud.githubusercontent.com/assets/7007826/11290513/7b753fa0-8f72-11e5-9f62-9ce8f9b2c5c8.png)

**Comment by kangxu** [comment]
Step4:
![image](https://cloud.githubusercontent.com/assets/7007826/11290534/b207bf8e-8f72-11e5-8dc8-1ef767aa806c.png)

**Comment by kangxu** [comment]
Step5:
![image](https://cloud.githubusercontent.com/assets/7007826/11290596/308a0448-8f73-11e5-9f4f-8ce33c75a5fd.png)

**Comment by kangxu** [comment]
Step6:
![image](https://cloud.githubusercontent.com/assets/7007826/11290611/4c10f5a0-8f73-11e5-8d80-413ec3cf36af.png)

**Comment by kangxu** [comment]
Step7:
![image](https://cloud.githubusercontent.com/assets/7007826/11290624/6b7848e4-8f73-11e5-8667-197b6343bb3a.png)

**Comment by kangxu** [comment]
Step8:
![image](https://cloud.githubusercontent.com/assets/7007826/11290654/bc753892-8f73-11e5-9e0f-41cbc35427dd.png)

**Comment by kangxu** [comment]
Step9:
![image](https://cloud.githubusercontent.com/assets/7007826/11290744/91f93d9c-8f74-11e5-9ede-575d29eb2917.png)

**Comment by kangxu** [comment]
Step10:
![image](https://cloud.githubusercontent.com/assets/7007826/11290754/ac2be412-8f74-11e5-8a93-55a90d55a782.png)

**Comment by kangxu** [comment]
Step11:
![image](https://cloud.githubusercontent.com/assets/7007826/11290765/c0579080-8f74-11e5-8f58-a5ebdc04693a.png)
