### ISSUE TITLE
XWalkViewWithScrollViewParentAsync is not working

### ISSUE THREAD

**Issue by AAverin** [crosswalk-project/crosswalk-test-suite#3409]
running XWalkViewWithScrollViewParentAsync shows nothing on `beta:18.48.477.6`

**Comment by zqzhang** [comment]
@jacky-young, @Shao-Feng this deserves an XWALK Jira bug, I think. Do you have one?

**Comment by jacky-young** [comment]
Hi @zqzhang This is the original bug [XWALK-4876](https://crosswalk-project.org/jira/browse/XWALK-4876), it's still unresolved. My pr is just a demonstration or usecase to show the problem, And after bug fixed, my case should work fine.

**Comment by zqzhang** [comment]
Thanks, closing this.
