### ISSUE TITLE
Web SQL Transfer Support?

### ISSUE THREAD

**Issue by gylippus** [crosswalk-project/crosswalk-test-suite#3647]
I see many references in the test code for Web SQL alongside localStorage and IndexDB in regards to validating that crosswalk can work well after upgrading using higher Crosswalk binary and runtime library. 

Mainly unsure because the tests are commented out here: https://github.com/crosswalk-project/crosswalk-test-suite/blob/master/usecase/usecase-cordova-android-tests/samples/Database/res/database_source/js/main.js, and that it is not mentioned here: https://crosswalk-project.org/blog/crosswalk-15-beta.html

I was hoping to just verify, **is Web SQL also migrated when upgrading a non-Crosswalk app to use Crosswalk?**

This may have been an issue/question suited for another repo, but all of my initial investigating pointed to more references here. 

Thank you.

**Comment by haoxli** [comment]
This feature will be supported in Crosswalk-21: [WALK-4488]
(https://crosswalk-project.org/jira/browse/XWALK-4488)
And I have submitted PR to add the test back for this feature：https://github.com/crosswalk-project/crosswalk-test-suite/pull/3551

**Comment by Honry** [comment]
Let's track this feature in [XWALK-4488]
(https://crosswalk-project.org/jira/browse/XWALK-4488).
