### ISSUE TITLE
Bug with many XwalView in activity (in fragments)

### ISSUE THREAD

**Issue by kenumir** [crosswalk-project/crosswalk-test-suite#779]
I write simple project using XWalkView 
https://github.com/kenumir/XWalkViewFragmentTest

When open more than one fragment with XWalkView view on background shows all the time first page, touch event is not working (new fragment ovelay with transparency page in background).

Everything is ok when use *replace* instead of *add* when fragment is created.
It looks like only one XWalkView can be used on activity?

Any solution of this problem?

**Comment by suleymanccelik** [comment]
Is there any update for the issue?

**Comment by zhuyongyong** [comment]
I build https://github.com/kenumir/XWalkViewFragmentTest app using crosswalk-14.43.343.6(in https://download.01.org/crosswalk/releases/crosswalk/android/beta/14.43.343.6/) and launch it,
But I do't encounter the “touch event is not working”  issue. 

Yes, at the same time, only one XWalkView can be used on activity.

**Comment by zqzhang** [comment]
Close as cannot be reproduce. If you still have issues please file a bug at https://crosswalk-project.org/jira/issues/, thanks.
